name: openSUSE/Tumbleweed / Qt latest
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildInContainer:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: get container ready for build
      run: |
        echo "--------------------------------------------------------------"
        echo "update distro and install dependencies"
        zypper -n install git gcc-c++ make autoconf automake libtool cmake libzip-devel \
        libxml2-devel libxslt-devel sqlite3-devel libusb-1_0-devel \
        libqt5-linguist-devel libqt5-qttools-devel libQt5WebKitWidgets-devel \
        libqt5-qtbase-devel libQt5WebKit5-devel libqt5-qtsvg-devel \
        libqt5-qtscript-devel libqt5-qtdeclarative-devel \
        libqt5-qtconnectivity-devel libqt5-qtlocation-devel libcurl-devel \
        libQt5QuickControls2-devel bluez-devel \
        which libgit2-devel libssh2-devel libmtp-devel \
        libQt5Charts5-devel

# if we want to run the tests below, add    xvfb-run

    - name: build Subsurface
      run: |
        echo "--------------------------------------------------------------"
        echo "building desktop"

        # now build for the desktop version (including WebKit)
        cd ..
        bash -e -x subsurface/scripts/build.sh -desktop -build-with-webkit

# let's not run the tests... to do that, we need to install 'xvfb-run' above
#   - name: test desktop build
#     run: |
#       echo "--------------------------------------------------------------"
#       echo "running tests for desktop"
#       cd build
#       xvfb-run --auto-servernum make check
